package src.Maps {
	/**
	 * ...
	 * @author Xiler
	 */
	public class TestMap5 extends Map implements IMap{
		public function TestMap5() {
			this._xmlData=
<data>
  <tile type="regTile" graphic="6" x="-6" y="0"/>
  <tile type="regTile" graphic="6" x="-5" y="0"/>
  <tile type="regTile" graphic="6" x="-4" y="0"/>
  <tile type="regTile" graphic="6" x="-3" y="0"/>
  <tile type="regTile" graphic="6" x="-2" y="0"/>
  <tile type="regTile" graphic="6" x="-1" y="0"/>
  <tile type="regTile" graphic="6" x="0" y="0"/>
  <tile type="regTile" graphic="6" x="1" y="0"/>
  <tile type="regTile" graphic="6" x="2" y="0"/>
  <tile type="regTile" graphic="6" x="3" y="0"/>
  <tile type="regTile" graphic="6" x="4" y="0"/>
  <tile type="regTile" graphic="6" x="5" y="0"/>
  <tile type="regTile" graphic="6" x="6" y="0"/>
  <tile type="regTile" graphic="6" x="7" y="0"/>
  <tile type="regTile" graphic="6" x="8" y="0"/>
  <tile type="regTile" graphic="6" x="8" y="-1"/>
  <tile type="regTile" graphic="6" x="-7" y="0"/>
  <tile type="regTile" graphic="6" x="-8" y="0"/>
  <tile type="regTile" graphic="6" x="-8" y="-1"/>
  <tile type="regTile" graphic="6" x="-8" y="-5"/>
  <tile type="regTile" graphic="6" x="1" y="-1"/>
  <tile type="regTile" graphic="6" x="0" y="-1"/>
  <tile type="regTile" graphic="6" x="-1" y="-1"/>
  <tile type="regTile" graphic="6" x="10" y="-2"/>
  <tile type="regTile" graphic="6" x="11" y="-2"/>
  <tile type="regTile" graphic="6" x="8" y="-5"/>
  <tile type="regTile" graphic="6" x="9" y="-5"/>
  <tile type="regTile" graphic="6" x="10" y="-5"/>
  <tile type="regTile" graphic="6" x="11" y="-5"/>
  <tile type="regTile" graphic="6" x="12" y="-2"/>
  <tile type="regTile" graphic="6" x="13" y="-2"/>
  <tile type="regTile" graphic="6" x="14" y="-2"/>
  <tile type="regTile" graphic="6" x="14" y="-3"/>
  <tile type="regTile" graphic="6" x="14" y="-4"/>
  <tile type="regTile" graphic="6" x="14" y="-5"/>
  <tile type="regTile" graphic="6" x="14" y="-6"/>
  <tile type="regTile" graphic="6" x="14" y="-7"/>
  <tile type="regTile" graphic="6" x="14" y="-8"/>
  <tile type="regTile" graphic="6" x="12" y="-8"/>
  <tile type="regTile" graphic="6" x="11" y="-8"/>
  <tile type="regTile" graphic="6" x="10" y="-8"/>
  <tile type="regTile" graphic="6" x="9" y="-8"/>
  <tile type="regTile" graphic="6" x="8" y="-8"/>
  <tile type="regTile" graphic="6" x="-9" y="-5"/>
  <tile type="regTile" graphic="6" x="-10" y="-5"/>
  <tile type="regTile" graphic="6" x="-11" y="-5"/>
  <tile type="regTile" graphic="6" x="-10" y="-2"/>
  <tile type="regTile" graphic="6" x="-11" y="-2"/>
  <tile type="regTile" graphic="6" x="-12" y="-2"/>
  <tile type="regTile" graphic="6" x="-13" y="-2"/>
  <tile type="regTile" graphic="6" x="-14" y="-3"/>
  <tile type="regTile" graphic="6" x="-14" y="-2"/>
  <tile type="regTile" graphic="6" x="-14" y="-4"/>
  <tile type="regTile" graphic="6" x="-14" y="-5"/>
  <tile type="regTile" graphic="6" x="-14" y="-6"/>
  <tile type="regTile" graphic="6" x="-14" y="-7"/>
  <tile type="regTile" graphic="6" x="-8" y="-8"/>
  <tile type="regTile" graphic="6" x="-9" y="-8"/>
  <tile type="regTile" graphic="6" x="-10" y="-8"/>
  <tile type="regTile" graphic="6" x="-11" y="-8"/>
  <tile type="regTile" graphic="6" x="-12" y="-8"/>
  <tile type="regTile" graphic="6" x="-14" y="-8"/>
  <tile type="regTile" graphic="6" x="7" y="-5"/>
  <tile type="regTile" graphic="6" x="6" y="-5"/>
  <tile type="regTile" graphic="6" x="5" y="-5"/>
  <tile type="regTile" graphic="6" x="4" y="-5"/>
  <tile type="regTile" graphic="6" x="1" y="-5"/>
  <tile type="regTile" graphic="6" x="0" y="-5"/>
  <tile type="regTile" graphic="6" x="-2" y="-5"/>
  <tile type="regTile" graphic="6" x="-4" y="-5"/>
  <tile type="regTile" graphic="6" x="-5" y="-5"/>
  <tile type="regTile" graphic="6" x="-6" y="-5"/>
  <tile type="regTile" graphic="6" x="-7" y="-5"/>
  <tile type="regTile" graphic="6" x="-3" y="-5"/>
  <tile type="regTile" graphic="6" x="-1" y="-5"/>
  <tile type="regTile" graphic="6" x="2" y="-5"/>
  <tile type="regTile" graphic="6" x="3" y="-5"/>
  <tile type="jumpTile" graphic="4" x="5" y="-8"/>
  <tile type="jumpTile" graphic="4" x="3" y="-8"/>
  <tile type="jumpTile" graphic="4" x="2" y="-8"/>
  <tile type="jumpTile" graphic="4" x="1" y="-8"/>
  <tile type="jumpTile" graphic="4" x="-1" y="-8"/>
  <tile type="jumpTile" graphic="4" x="-2" y="-8"/>
  <tile type="jumpTile" graphic="4" x="-3" y="-8"/>
  <tile type="jumpTile" graphic="4" x="-4" y="-8"/>
  <tile type="jumpTile" graphic="4" x="-5" y="-8"/>
  <tile type="jumpTile" graphic="4" x="4" y="-8"/>
  <tile type="jumpTile" graphic="4" x="0" y="-8"/>
  <tile type="regTile" graphic="6" x="8" y="-9"/>
  <tile type="regTile" graphic="6" x="-8" y="-9"/>
  <tile type="regTile" graphic="6" x="-9" y="0"/>
  <tile type="regTile" graphic="6" x="-11" y="0"/>
  <tile type="regTile" graphic="6" x="-13" y="0"/>
  <tile type="regTile" graphic="6" x="-14" y="0"/>
  <tile type="regTile" graphic="6" x="-14" y="-1"/>
  <tile type="regTile" graphic="6" x="-13" y="-1"/>
  <tile type="regTile" graphic="6" x="-12" y="-1"/>
  <tile type="regTile" graphic="6" x="-11" y="-1"/>
  <tile type="regTile" graphic="6" x="-10" y="-1"/>
  <tile type="regTile" graphic="6" x="-10" y="0"/>
  <tile type="regTile" graphic="6" x="-12" y="0"/>
  <tile type="regTile" graphic="6" x="-9" y="-1"/>
  <tile type="regTile" graphic="6" x="14" y="-1"/>
  <tile type="regTile" graphic="6" x="14" y="0"/>
  <tile type="regTile" graphic="6" x="13" y="0"/>
  <tile type="regTile" graphic="6" x="12" y="0"/>
  <tile type="regTile" graphic="6" x="11" y="0"/>
  <tile type="regTile" graphic="6" x="10" y="0"/>
  <tile type="regTile" graphic="6" x="9" y="0"/>
  <tile type="regTile" graphic="6" x="9" y="-1"/>
  <tile type="regTile" graphic="6" x="10" y="-1"/>
  <tile type="regTile" graphic="6" x="11" y="-1"/>
  <tile type="regTile" graphic="6" x="12" y="-1"/>
  <tile type="regTile" graphic="6" x="13" y="-1"/>
  <tile type="regTile" graphic="6" x="14" y="-9"/>
  <tile type="regTile" graphic="6" x="14" y="-10"/>
  <tile type="regTile" graphic="6" x="14" y="-11"/>
  <tile type="regTile" graphic="6" x="14" y="-12"/>
  <tile type="regTile" graphic="6" x="14" y="-13"/>
  <tile type="regTile" graphic="6" x="8" y="-13"/>
  <tile type="regTile" graphic="6" x="13" y="-13"/>
  <tile type="regTile" graphic="6" x="12" y="-13"/>
  <tile type="regTile" graphic="6" x="10" y="-13"/>
  <tile type="regTile" graphic="6" x="9" y="-13"/>
  <tile type="regTile" graphic="6" x="11" y="-13"/>
  <tile type="regTile" graphic="6" x="-14" y="-9"/>
  <tile type="regTile" graphic="6" x="-14" y="-10"/>
  <tile type="regTile" graphic="6" x="-14" y="-11"/>
  <tile type="regTile" graphic="6" x="-14" y="-12"/>
  <tile type="regTile" graphic="6" x="-14" y="-13"/>
  <tile type="regTile" graphic="6" x="-13" y="-13"/>
  <tile type="regTile" graphic="6" x="-11" y="-13"/>
  <tile type="regTile" graphic="6" x="-10" y="-13"/>
  <tile type="regTile" graphic="6" x="-9" y="-13"/>
  <tile type="regTile" graphic="6" x="-8" y="-13"/>
  <tile type="regTile" graphic="6" x="-12" y="-13"/>
  <tile type="regTile" graphic="6" x="4" y="-12"/>
  <tile type="regTile" graphic="6" x="3" y="-12"/>
  <tile type="regTile" graphic="6" x="2" y="-12"/>
  <tile type="regTile" graphic="6" x="1" y="-12"/>
  <tile type="regTile" graphic="6" x="0" y="-12"/>
  <tile type="regTile" graphic="6" x="-1" y="-12"/>
  <tile type="regTile" graphic="6" x="-2" y="-12"/>
  <tile type="regTile" graphic="6" x="-3" y="-12"/>
  <tile type="regTile" graphic="6" x="-4" y="-12"/>
  <tile type="regTile" graphic="6" x="8" y="-12"/>
  <tile type="regTile" graphic="6" x="-8" y="-12"/>
  <tile type="regTile" graphic="6" x="-3" y="-15"/>
  <tile type="regTile" graphic="6" x="-2" y="-15"/>
  <tile type="regTile" graphic="6" x="0" y="-15"/>
  <tile type="regTile" graphic="6" x="1" y="-15"/>
  <tile type="regTile" graphic="6" x="2" y="-15"/>
  <tile type="regTile" graphic="6" x="3" y="-15"/>
  <tile type="regTile" graphic="6" x="-1" y="-15"/>
  <tile type="regTile" graphic="6" x="-4" y="-15"/>
  <tile type="regTile" graphic="6" x="-5" y="-15"/>
  <tile type="regTile" graphic="6" x="-6" y="-15"/>
  <tile type="regTile" graphic="6" x="-7" y="-15"/>
  <tile type="regTile" graphic="6" x="-8" y="-15"/>
  <tile type="regTile" graphic="6" x="-9" y="-15"/>
  <tile type="regTile" graphic="6" x="-10" y="-15"/>
  <tile type="regTile" graphic="6" x="-13" y="-15"/>
  <tile type="regTile" graphic="6" x="-11" y="-15"/>
  <tile type="regTile" graphic="6" x="-12" y="-15"/>
  <tile type="regTile" graphic="6" x="-14" y="-15"/>
  <tile type="regTile" graphic="6" x="-14" y="-14"/>
  <tile type="regTile" graphic="6" x="-13" y="-14"/>
  <tile type="regTile" graphic="6" x="-12" y="-14"/>
  <tile type="regTile" graphic="6" x="-11" y="-14"/>
  <tile type="regTile" graphic="6" x="-10" y="-14"/>
  <tile type="regTile" graphic="6" x="-9" y="-14"/>
  <tile type="regTile" graphic="6" x="-8" y="-14"/>
  <tile type="regTile" graphic="6" x="14" y="-14"/>
  <tile type="regTile" graphic="6" x="14" y="-15"/>
  <tile type="regTile" graphic="6" x="13" y="-15"/>
  <tile type="regTile" graphic="6" x="13" y="-14"/>
  <tile type="regTile" graphic="6" x="12" y="-14"/>
  <tile type="regTile" graphic="6" x="12" y="-15"/>
  <tile type="regTile" graphic="6" x="11" y="-15"/>
  <tile type="regTile" graphic="6" x="11" y="-14"/>
  <tile type="regTile" graphic="6" x="10" y="-14"/>
  <tile type="regTile" graphic="6" x="10" y="-15"/>
  <tile type="regTile" graphic="6" x="9" y="-14"/>
  <tile type="regTile" graphic="6" x="9" y="-15"/>
  <tile type="regTile" graphic="6" x="8" y="-14"/>
  <tile type="regTile" graphic="6" x="8" y="-15"/>
  <tile type="regTile" graphic="6" x="7" y="-15"/>
  <tile type="regTile" graphic="6" x="6" y="-15"/>
  <tile type="regTile" graphic="6" x="5" y="-15"/>
  <tile type="regTile" graphic="6" x="4" y="-15"/>
  <marker type="1" x="0" y="-2"/>
  <mapRect x="-14" y="-15" width="29" height="16"/>
</data>
		}
	}
}