package src.Maps {
	/**
	 * ...
	 * @author Xiler
	 */
	public class TestMap extends Map implements IMap{
		public function TestMap() {
			this._xmlData=
			<data>
			  <tile type="regTile" graphic="3" x="-1" y="-1"/>
			  <tile type="regTile" graphic="3" x="-1" y="0"/>
			  <tile type="regTile" graphic="3" x="0" y="0"/>
			  <tile type="regTile" graphic="3" x="0" y="-1"/>
			  <tile type="regTile" graphic="2" x="0" y="-2"/>
			  <tile type="regTile" graphic="2" x="-1" y="-2"/>
			  <tile type="regTile" graphic="2" x="-2" y="-1"/>
			  <tile type="regTile" graphic="2" x="-2" y="0"/>
			  <tile type="regTile" graphic="2" x="1" y="0"/>
			  <tile type="regTile" graphic="2" x="1" y="-1"/>
			  <tile type="regTile" graphic="2" x="2" y="-1"/>
			  <tile type="regTile" graphic="2" x="-3" y="-1"/>
			  <tile type="regTile" graphic="2" x="-4" y="-1"/>
			  <tile type="regTile" graphic="2" x="-5" y="-1"/>
			  <tile type="regTile" graphic="2" x="-6" y="-1"/>
			  <tile type="regTile" graphic="2" x="3" y="-1"/>
			  <tile type="regTile" graphic="2" x="4" y="-1"/>
			  <tile type="regTile" graphic="2" x="5" y="-1"/>
			  <tile type="regTile" graphic="2" x="-6" y="2"/>
			  <tile type="regTile" graphic="2" x="-5" y="2"/>
			  <tile type="regTile" graphic="2" x="-4" y="2"/>
			  <tile type="regTile" graphic="2" x="3" y="2"/>
			  <tile type="regTile" graphic="2" x="4" y="2"/>
			  <tile type="regTile" graphic="2" x="5" y="2"/>
			  <tile type="regTile" graphic="2" x="6" y="2"/>
			  <tile type="regTile" graphic="2" x="7" y="2"/>
			  <tile type="regTile" graphic="2" x="8" y="2"/>
			  <tile type="regTile" graphic="2" x="8" y="1"/>
			  <tile type="regTile" graphic="2" x="8" y="0"/>
			  <tile type="regTile" graphic="2" x="8" y="-1"/>
			  <tile type="regTile" graphic="2" x="8" y="-2"/>
			  <tile type="regTile" graphic="2" x="-7" y="2"/>
			  <tile type="regTile" graphic="2" x="-8" y="2"/>
			  <tile type="regTile" graphic="2" x="-9" y="2"/>
			  <tile type="regTile" graphic="2" x="-9" y="1"/>
			  <tile type="regTile" graphic="2" x="-9" y="0"/>
			  <tile type="regTile" graphic="2" x="-9" y="-1"/>
			  <tile type="regTile" graphic="2" x="-9" y="-2"/>
			  <tile type="regTile" graphic="2" x="0" y="1"/>
			  <tile type="regTile" graphic="2" x="-1" y="1"/>
			  <tile type="regTile" graphic="2" x="3" y="3"/>
			  <tile type="regTile" graphic="2" x="3" y="4"/>
			  <tile type="regTile" graphic="2" x="-4" y="4"/>
			  <tile type="regTile" graphic="2" x="-4" y="3"/>
			  <tile type="regTile" graphic="2" x="2" y="4"/>
			  <tile type="regTile" graphic="2" x="1" y="4"/>
			  <tile type="regTile" graphic="2" x="0" y="4"/>
			  <tile type="regTile" graphic="2" x="-1" y="4"/>
			  <tile type="regTile" graphic="2" x="-2" y="4"/>
			  <tile type="regTile" graphic="2" x="-3" y="4"/>
			  <tile type="regTile" graphic="2" x="-2" y="-2"/>
			  <tile type="regTile" graphic="2" x="1" y="-2"/>
			  <tile type="regTile" graphic="2" x="0" y="-3"/>
			  <tile type="regTile" graphic="2" x="-1" y="-3"/>
			  <tile type="regTile" graphic="2" x="9" y="-2"/>
			  <tile type="regTile" graphic="2" x="10" y="-2"/>
			  <tile type="regTile" graphic="2" x="11" y="-2"/>
			  <tile type="regTile" graphic="2" x="12" y="-2"/>
			  <tile type="regTile" graphic="2" x="13" y="-2"/>
			  <tile type="regTile" graphic="2" x="14" y="-2"/>
			  <tile type="regTile" graphic="2" x="15" y="-2"/>
			  <tile type="regTile" graphic="2" x="16" y="-2"/>
			  <tile type="regTile" graphic="2" x="17" y="-2"/>
			  <tile type="regTile" graphic="2" x="17" y="-3"/>
			  <tile type="regTile" graphic="2" x="-10" y="-2"/>
			  <tile type="regTile" graphic="2" x="-11" y="-2"/>
			  <tile type="regTile" graphic="2" x="-12" y="-2"/>
			  <tile type="regTile" graphic="2" x="-13" y="-2"/>
			  <tile type="regTile" graphic="2" x="-14" y="-2"/>
			  <tile type="regTile" graphic="2" x="-15" y="-2"/>
			  <tile type="regTile" graphic="2" x="-16" y="-2"/>
			  <tile type="regTile" graphic="2" x="-17" y="-2"/>
			  <tile type="regTile" graphic="2" x="-18" y="-2"/>
			  <tile type="regTile" graphic="2" x="-18" y="-3"/>
			  <tile type="regTile" graphic="2" x="-18" y="-4"/>
			  <tile type="regTile" graphic="2" x="-18" y="-5"/>
			  <tile type="regTile" graphic="2" x="17" y="-4"/>
			  <tile type="regTile" graphic="2" x="17" y="-5"/>
			  <tile type="regTile" graphic="2" x="17" y="-6"/>
			  <tile type="regTile" graphic="2" x="17" y="-7"/>
			  <tile type="regTile" graphic="2" x="17" y="-8"/>
			  <tile type="regTile" graphic="2" x="17" y="-9"/>
			  <tile type="regTile" graphic="2" x="17" y="-10"/>
			  <tile type="regTile" graphic="2" x="17" y="-11"/>
			  <tile type="regTile" graphic="2" x="-18" y="-6"/>
			  <tile type="regTile" graphic="2" x="-18" y="-7"/>
			  <tile type="regTile" graphic="2" x="-18" y="-8"/>
			  <tile type="regTile" graphic="2" x="-18" y="-9"/>
			  <tile type="regTile" graphic="2" x="-18" y="-10"/>
			  <tile type="regTile" graphic="2" x="-18" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-17" y="-8"/>
			  <tile type="jumpTile" graphic="1" x="-16" y="-8"/>
			  <tile type="jumpTile" graphic="1" x="-17" y="-5"/>
			  <tile type="jumpTile" graphic="1" x="-16" y="-5"/>
			  <tile type="jumpTile" graphic="1" x="-17" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-16" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="16" y="-5"/>
			  <tile type="jumpTile" graphic="1" x="15" y="-5"/>
			  <tile type="jumpTile" graphic="1" x="16" y="-8"/>
			  <tile type="jumpTile" graphic="1" x="15" y="-8"/>
			  <tile type="jumpTile" graphic="1" x="16" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="15" y="-11"/>
			  <tile type="regTile" graphic="2" x="-11" y="-3"/>
			  <tile type="regTile" graphic="2" x="-12" y="-3"/>
			  <tile type="regTile" graphic="2" x="-13" y="-3"/>
			  <tile type="regTile" graphic="2" x="10" y="-3"/>
			  <tile type="regTile" graphic="2" x="11" y="-3"/>
			  <tile type="regTile" graphic="2" x="12" y="-3"/>
			  <tile type="regTile" graphic="2" x="-2" y="-11"/>
			  <tile type="regTile" graphic="2" x="1" y="-11"/>
			  <tile type="regTile" graphic="2" x="-1" y="-9"/>
			  <tile type="regTile" graphic="2" x="0" y="-9"/>
			  <tile type="regTile" graphic="2" x="1" y="-10"/>
			  <tile type="regTile" graphic="2" x="2" y="-11"/>
			  <tile type="regTile" graphic="2" x="-2" y="-10"/>
			  <tile type="regTile" graphic="2" x="-3" y="-11"/>
			  <tile type="regTile" graphic="2" x="3" y="-8"/>
			  <tile type="regTile" graphic="2" x="4" y="-9"/>
			  <tile type="regTile" graphic="2" x="5" y="-10"/>
			  <tile type="regTile" graphic="2" x="4" y="-8"/>
			  <tile type="regTile" graphic="2" x="6" y="-10"/>
			  <tile type="regTile" graphic="2" x="5" y="-9"/>
			  <tile type="regTile" graphic="2" x="6" y="-11"/>
			  <tile type="regTile" graphic="2" x="7" y="-11"/>
			  <tile type="regTile" graphic="2" x="-4" y="-8"/>
			  <tile type="regTile" graphic="2" x="-5" y="-8"/>
			  <tile type="regTile" graphic="2" x="-5" y="-9"/>
			  <tile type="regTile" graphic="2" x="-6" y="-9"/>
			  <tile type="regTile" graphic="2" x="-6" y="-10"/>
			  <tile type="regTile" graphic="2" x="-7" y="-10"/>
			  <tile type="regTile" graphic="2" x="-7" y="-11"/>
			  <tile type="regTile" graphic="2" x="-8" y="-11"/>
			  <tile type="regTile" graphic="2" x="3" y="-7"/>
			  <tile type="regTile" graphic="2" x="3" y="-6"/>
			  <tile type="regTile" graphic="2" x="2" y="-6"/>
			  <tile type="regTile" graphic="2" x="-4" y="-7"/>
			  <tile type="regTile" graphic="2" x="-4" y="-6"/>
			  <tile type="regTile" graphic="2" x="-3" y="-6"/>
			  <tile type="regTile" graphic="2" x="-8" y="-12"/>
			  <tile type="regTile" graphic="2" x="-8" y="-13"/>
			  <tile type="regTile" graphic="2" x="-8" y="-14"/>
			  <tile type="regTile" graphic="2" x="-8" y="-15"/>
			  <tile type="regTile" graphic="2" x="7" y="-12"/>
			  <tile type="regTile" graphic="2" x="7" y="-13"/>
			  <tile type="regTile" graphic="2" x="7" y="-14"/>
			  <tile type="regTile" graphic="2" x="7" y="-15"/>
			  <tile type="regTile" graphic="2" x="-2" y="-17"/>
			  <tile type="regTile" graphic="2" x="-1" y="-16"/>
			  <tile type="regTile" graphic="2" x="1" y="-17"/>
			  <tile type="regTile" graphic="2" x="0" y="-16"/>
			  <tile type="jumpTile" graphic="1" x="-1" y="-15"/>
			  <tile type="jumpTile" graphic="1" x="0" y="-15"/>
			  <tile type="regTile" graphic="2" x="-2" y="-12"/>
			  <tile type="regTile" graphic="2" x="1" y="-12"/>
			  <tile type="regTile" graphic="2" x="-18" y="-12"/>
			  <tile type="regTile" graphic="2" x="-18" y="-13"/>
			  <tile type="regTile" graphic="2" x="-18" y="-14"/>
			  <tile type="regTile" graphic="2" x="-17" y="-15"/>
			  <tile type="regTile" graphic="2" x="-16" y="-16"/>
			  <tile type="regTile" graphic="2" x="-15" y="-17"/>
			  <tile type="regTile" graphic="2" x="-13" y="-19"/>
			  <tile type="regTile" graphic="2" x="-14" y="-18"/>
			  <tile type="regTile" graphic="2" x="17" y="-14"/>
			  <tile type="regTile" graphic="2" x="17" y="-13"/>
			  <tile type="regTile" graphic="2" x="17" y="-12"/>
			  <tile type="regTile" graphic="2" x="16" y="-15"/>
			  <tile type="regTile" graphic="2" x="15" y="-16"/>
			  <tile type="regTile" graphic="2" x="14" y="-17"/>
			  <tile type="regTile" graphic="2" x="13" y="-18"/>
			  <tile type="regTile" graphic="2" x="12" y="-19"/>
			  <tile type="jumpTile" graphic="1" x="-6" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="-5" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="5" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="4" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="3" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="2" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="1" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="0" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="-1" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="-2" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="-3" y="-13"/>
			  <tile type="jumpTile" graphic="1" x="-4" y="-13"/>
			  <tile type="regTile" graphic="3" x="0" y="-10"/>
			  <tile type="regTile" graphic="3" x="-1" y="-10"/>
			  <tile type="regTile" graphic="2" x="0" y="-11"/>
			  <tile type="regTile" graphic="2" x="-1" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="9" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="10" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="11" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="12" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="13" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="14" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="8" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-15" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-14" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-13" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-12" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-11" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-10" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-9" y="-11"/>
			  <tile type="jumpTile" graphic="1" x="-9" y="-15"/>
			  <tile type="jumpTile" graphic="1" x="-10" y="-15"/>
			  <tile type="jumpTile" graphic="1" x="-11" y="-15"/>
			  <tile type="jumpTile" graphic="1" x="8" y="-15"/>
			  <tile type="jumpTile" graphic="1" x="9" y="-15"/>
			  <tile type="jumpTile" graphic="1" x="10" y="-15"/>
			  <tile type="regTile" graphic="2" x="11" y="-20"/>
			  <tile type="regTile" graphic="2" x="10" y="-20"/>
			  <tile type="regTile" graphic="2" x="9" y="-20"/>
			  <tile type="regTile" graphic="2" x="8" y="-20"/>
			  <tile type="regTile" graphic="2" x="7" y="-20"/>
			  <tile type="regTile" graphic="2" x="6" y="-20"/>
			  <tile type="regTile" graphic="2" x="5" y="-20"/>
			  <tile type="regTile" graphic="2" x="4" y="-20"/>
			  <tile type="regTile" graphic="2" x="3" y="-20"/>
			  <tile type="regTile" graphic="2" x="2" y="-20"/>
			  <tile type="regTile" graphic="2" x="1" y="-20"/>
			  <tile type="regTile" graphic="2" x="0" y="-20"/>
			  <tile type="regTile" graphic="2" x="-1" y="-20"/>
			  <tile type="regTile" graphic="2" x="-2" y="-20"/>
			  <tile type="regTile" graphic="2" x="-3" y="-20"/>
			  <tile type="regTile" graphic="2" x="-4" y="-20"/>
			  <tile type="regTile" graphic="2" x="-5" y="-20"/>
			  <tile type="regTile" graphic="2" x="-6" y="-20"/>
			  <tile type="regTile" graphic="2" x="-7" y="-20"/>
			  <tile type="regTile" graphic="2" x="-8" y="-20"/>
			  <tile type="regTile" graphic="2" x="-9" y="-20"/>
			  <tile type="regTile" graphic="2" x="-10" y="-20"/>
			  <tile type="regTile" graphic="2" x="-11" y="-20"/>
			  <tile type="regTile" graphic="2" x="-12" y="-20"/>
			  <marker type="1" x="-17" y="-3"/>
			  <mapRect x="-18" y="-20" width="36" height="25"/>
			</data>
		}
	}
}