package src.Maps {
	/**
	 * ...
	 * @author Xiler
	 */
	public class TestMap2 extends Map implements IMap{
		public function TestMap2() {
			this._xmlData=
				<data>
				  <tile type="regTile" graphic="4" x="0" y="0"/>
				  <tile type="regTile" graphic="4" x="1" y="0"/>
				  <tile type="regTile" graphic="4" x="2" y="0"/>
				  <tile type="regTile" graphic="4" x="3" y="0"/>
				  <tile type="regTile" graphic="4" x="4" y="0"/>
				  <tile type="regTile" graphic="4" x="5" y="0"/>
				  <tile type="regTile" graphic="4" x="6" y="0"/>
				  <tile type="regTile" graphic="4" x="7" y="0"/>
				  <tile type="regTile" graphic="4" x="-1" y="0"/>
				  <tile type="regTile" graphic="4" x="-2" y="0"/>
				  <tile type="regTile" graphic="4" x="-3" y="0"/>
				  <tile type="regTile" graphic="4" x="-4" y="0"/>
				  <tile type="regTile" graphic="4" x="-5" y="0"/>
				  <tile type="regTile" graphic="2" x="9" y="-1"/>
				  <tile type="regTile" graphic="2" x="9" y="-2"/>
				  <tile type="regTile" graphic="2" x="9" y="-3"/>
				  <tile type="regTile" graphic="2" x="9" y="-4"/>
				  <tile type="regTile" graphic="2" x="9" y="-5"/>
				  <tile type="regTile" graphic="2" x="-7" y="-1"/>
				  <tile type="regTile" graphic="2" x="-7" y="-2"/>
				  <tile type="regTile" graphic="2" x="-7" y="-5"/>
				  <tile type="regTile" graphic="2" x="-7" y="-4"/>
				  <tile type="regTile" graphic="2" x="-7" y="-3"/>
				  <tile type="jumpTile" graphic="2" x="4" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="3" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="5" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="6" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="7" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="8" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="8" y="-4"/>
				  <tile type="jumpTile" graphic="2" x="7" y="-4"/>
				  <tile type="jumpTile" graphic="2" x="-1" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="-2" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="-3" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="-4" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="-5" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="-6" y="-2"/>
				  <tile type="jumpTile" graphic="2" x="-5" y="-4"/>
				  <tile type="jumpTile" graphic="2" x="-6" y="-4"/>
				  <tile type="regTile" graphic="2" x="-7" y="0"/>
				  <tile type="regTile" graphic="2" x="-7" y="1"/>
				  <tile type="regTile" graphic="2" x="-7" y="2"/>
				  <tile type="regTile" graphic="2" x="-7" y="3"/>
				  <tile type="regTile" graphic="2" x="-7" y="4"/>
				  <tile type="regTile" graphic="2" x="-7" y="5"/>
				  <tile type="regTile" graphic="2" x="9" y="0"/>
				  <tile type="regTile" graphic="2" x="9" y="1"/>
				  <tile type="regTile" graphic="2" x="9" y="2"/>
				  <tile type="regTile" graphic="2" x="9" y="3"/>
				  <tile type="regTile" graphic="2" x="9" y="4"/>
				  <tile type="regTile" graphic="2" x="9" y="5"/>
				  <tile type="regTile" graphic="2" x="-7" y="6"/>
				  <tile type="regTile" graphic="2" x="-7" y="7"/>
				  <tile type="regTile" graphic="2" x="-7" y="8"/>
				  <tile type="regTile" graphic="2" x="9" y="6"/>
				  <tile type="regTile" graphic="2" x="9" y="7"/>
				  <tile type="regTile" graphic="2" x="9" y="8"/>
				  <tile type="regTile" graphic="1" x="9" y="11"/>
				  <tile type="regTile" graphic="1" x="8" y="11"/>
				  <tile type="regTile" graphic="1" x="7" y="11"/>
				  <tile type="regTile" graphic="1" x="6" y="11"/>
				  <tile type="regTile" graphic="1" x="5" y="11"/>
				  <tile type="regTile" graphic="1" x="4" y="11"/>
				  <tile type="regTile" graphic="1" x="3" y="11"/>
				  <tile type="regTile" graphic="1" x="2" y="11"/>
				  <tile type="regTile" graphic="1" x="1" y="11"/>
				  <tile type="regTile" graphic="1" x="0" y="11"/>
				  <tile type="regTile" graphic="1" x="-1" y="11"/>
				  <tile type="regTile" graphic="1" x="-2" y="11"/>
				  <tile type="regTile" graphic="1" x="-3" y="11"/>
				  <tile type="regTile" graphic="2" x="-7" y="9"/>
				  <tile type="regTile" graphic="2" x="-7" y="10"/>
				  <tile type="regTile" graphic="2" x="-7" y="11"/>
				  <tile type="regTile" graphic="1" x="10" y="11"/>
				  <tile type="regTile" graphic="1" x="11" y="11"/>
				  <tile type="regTile" graphic="1" x="12" y="10"/>
				  <tile type="regTile" graphic="1" x="13" y="10"/>
				  <tile type="regTile" graphic="1" x="13" y="9"/>
				  <tile type="regTile" graphic="1" x="14" y="9"/>
				  <tile type="regTile" graphic="1" x="15" y="8"/>
				  <tile type="regTile" graphic="1" x="16" y="7"/>
				  <tile type="regTile" graphic="1" x="17" y="7"/>
				  <tile type="regTile" graphic="1" x="17" y="6"/>
				  <tile type="regTile" graphic="1" x="18" y="6"/>
				  <tile type="regTile" graphic="1" x="19" y="6"/>
				  <tile type="regTile" graphic="1" x="20" y="7"/>
				  <tile type="regTile" graphic="1" x="21" y="7"/>
				  <tile type="regTile" graphic="1" x="21" y="8"/>
				  <tile type="regTile" graphic="1" x="22" y="8"/>
				  <tile type="regTile" graphic="1" x="22" y="7"/>
				  <tile type="regTile" graphic="1" x="23" y="7"/>
				  <tile type="regTile" graphic="1" x="24" y="7"/>
				  <tile type="regTile" graphic="1" x="24" y="6"/>
				  <tile type="regTile" graphic="1" x="25" y="6"/>
				  <tile type="regTile" graphic="1" x="25" y="5"/>
				  <tile type="regTile" graphic="1" x="26" y="5"/>
				  <tile type="regTile" graphic="1" x="26" y="4"/>
				  <tile type="regTile" graphic="1" x="27" y="4"/>
				  <tile type="regTile" graphic="1" x="28" y="4"/>
				  <tile type="regTile" graphic="1" x="29" y="3"/>
				  <tile type="regTile" graphic="1" x="31" y="5"/>
				  <tile type="regTile" graphic="1" x="32" y="5"/>
				  <tile type="regTile" graphic="1" x="32" y="6"/>
				  <tile type="regTile" graphic="1" x="33" y="6"/>
				  <tile type="regTile" graphic="1" x="33" y="7"/>
				  <tile type="regTile" graphic="1" x="34" y="7"/>
				  <tile type="regTile" graphic="1" x="35" y="7"/>
				  <tile type="regTile" graphic="1" x="36" y="7"/>
				  <tile type="regTile" graphic="1" x="37" y="8"/>
				  <tile type="regTile" graphic="1" x="38" y="8"/>
				  <tile type="regTile" graphic="1" x="39" y="7"/>
				  <tile type="regTile" graphic="1" x="40" y="7"/>
				  <tile type="regTile" graphic="1" x="40" y="6"/>
				  <tile type="regTile" graphic="1" x="41" y="6"/>
				  <tile type="regTile" graphic="1" x="41" y="5"/>
				  <tile type="regTile" graphic="1" x="41" y="4"/>
				  <tile type="regTile" graphic="1" x="42" y="3"/>
				  <tile type="regTile" graphic="1" x="43" y="3"/>
				  <tile type="regTile" graphic="1" x="43" y="4"/>
				  <tile type="regTile" graphic="1" x="45" y="4"/>
				  <tile type="regTile" graphic="1" x="46" y="3"/>
				  <tile type="regTile" graphic="1" x="47" y="3"/>
				  <tile type="regTile" graphic="1" x="47" y="2"/>
				  <tile type="regTile" graphic="1" x="47" y="1"/>
				  <tile type="regTile" graphic="1" x="47" y="0"/>
				  <tile type="regTile" graphic="1" x="44" y="4"/>
				  <tile type="regTile" graphic="1" x="48" y="-1"/>
				  <tile type="regTile" graphic="1" x="48" y="-2"/>
				  <tile type="regTile" graphic="1" x="48" y="-3"/>
				  <tile type="regTile" graphic="1" x="49" y="-3"/>
				  <tile type="regTile" graphic="1" x="49" y="-4"/>
				  <tile type="regTile" graphic="1" x="50" y="-4"/>
				  <tile type="regTile" graphic="1" x="50" y="-5"/>
				  <tile type="regTile" graphic="1" x="46" y="1"/>
				  <tile type="regTile" graphic="1" x="46" y="2"/>
				  <tile type="regTile" graphic="1" x="45" y="3"/>
				  <tile type="regTile" graphic="1" x="30" y="4"/>
				  <tile type="regTile" graphic="1" x="12" y="11"/>
				  <tile type="regTile" graphic="1" x="13" y="11"/>
				  <tile type="regTile" graphic="1" x="14" y="10"/>
				  <tile type="regTile" graphic="1" x="15" y="10"/>
				  <tile type="regTile" graphic="1" x="15" y="9"/>
				  <tile type="regTile" graphic="1" x="16" y="9"/>
				  <tile type="regTile" graphic="1" x="16" y="8"/>
				  <tile type="regTile" graphic="1" x="17" y="8"/>
				  <tile type="regTile" graphic="1" x="18" y="8"/>
				  <tile type="regTile" graphic="1" x="19" y="8"/>
				  <tile type="regTile" graphic="1" x="20" y="8"/>
				  <tile type="regTile" graphic="1" x="19" y="7"/>
				  <tile type="regTile" graphic="1" x="18" y="7"/>
				  <tile type="regTile" graphic="1" x="23" y="8"/>
				  <tile type="regTile" graphic="1" x="24" y="8"/>
				  <tile type="regTile" graphic="1" x="25" y="7"/>
				  <tile type="regTile" graphic="1" x="26" y="7"/>
				  <tile type="regTile" graphic="1" x="26" y="6"/>
				  <tile type="regTile" graphic="1" x="27" y="6"/>
				  <tile type="regTile" graphic="1" x="27" y="5"/>
				  <tile type="regTile" graphic="1" x="28" y="5"/>
				  <tile type="regTile" graphic="1" x="29" y="5"/>
				  <tile type="regTile" graphic="1" x="29" y="4"/>
				  <tile type="regTile" graphic="1" x="30" y="5"/>
				  <tile type="regTile" graphic="1" x="30" y="6"/>
				  <tile type="regTile" graphic="1" x="31" y="6"/>
				  <tile type="regTile" graphic="1" x="31" y="7"/>
				  <tile type="regTile" graphic="1" x="32" y="7"/>
				  <tile type="regTile" graphic="1" x="30" y="7"/>
				  <tile type="regTile" graphic="1" x="29" y="6"/>
				  <tile type="regTile" graphic="1" x="28" y="6"/>
				  <tile type="regTile" graphic="1" x="29" y="7"/>
				  <tile type="regTile" graphic="1" x="31" y="8"/>
				  <tile type="regTile" graphic="1" x="32" y="8"/>
				  <tile type="regTile" graphic="1" x="33" y="8"/>
				  <tile type="regTile" graphic="1" x="34" y="8"/>
				  <tile type="regTile" graphic="1" x="35" y="8"/>
				  <tile type="regTile" graphic="1" x="36" y="8"/>
				  <tile type="regTile" graphic="1" x="39" y="8"/>
				  <tile type="regTile" graphic="1" x="40" y="8"/>
				  <tile type="regTile" graphic="1" x="39" y="9"/>
				  <tile type="regTile" graphic="1" x="38" y="9"/>
				  <tile type="regTile" graphic="1" x="37" y="9"/>
				  <tile type="regTile" graphic="1" x="36" y="9"/>
				  <tile type="regTile" graphic="1" x="41" y="7"/>
				  <tile type="regTile" graphic="1" x="42" y="6"/>
				  <tile type="regTile" graphic="1" x="42" y="5"/>
				  <tile type="regTile" graphic="1" x="42" y="4"/>
				  <tile type="regTile" graphic="1" x="42" y="7"/>
				  <tile type="regTile" graphic="1" x="43" y="7"/>
				  <tile type="regTile" graphic="1" x="43" y="6"/>
				  <tile type="regTile" graphic="1" x="44" y="6"/>
				  <tile type="regTile" graphic="1" x="44" y="5"/>
				  <tile type="regTile" graphic="1" x="45" y="5"/>
				  <tile type="regTile" graphic="1" x="46" y="4"/>
				  <tile type="regTile" graphic="1" x="43" y="5"/>
				  <tile type="regTile" graphic="1" x="48" y="2"/>
				  <tile type="regTile" graphic="1" x="48" y="1"/>
				  <tile type="regTile" graphic="1" x="48" y="0"/>
				  <tile type="regTile" graphic="1" x="49" y="0"/>
				  <tile type="regTile" graphic="1" x="49" y="-1"/>
				  <tile type="regTile" graphic="1" x="49" y="-2"/>
				  <tile type="regTile" graphic="1" x="50" y="-2"/>
				  <tile type="regTile" graphic="1" x="50" y="-3"/>
				  <tile type="regTile" graphic="1" x="17" y="9"/>
				  <tile type="regTile" graphic="1" x="16" y="10"/>
				  <tile type="regTile" graphic="1" x="15" y="11"/>
				  <tile type="regTile" graphic="1" x="14" y="11"/>
				  <tile type="regTile" graphic="1" x="27" y="7"/>
				  <tile type="regTile" graphic="1" x="28" y="7"/>
				  <tile type="regTile" graphic="1" x="35" y="9"/>
				  <tile type="regTile" graphic="1" x="38" y="10"/>
				  <tile type="regTile" graphic="1" x="39" y="10"/>
				  <tile type="regTile" graphic="1" x="40" y="10"/>
				  <tile type="regTile" graphic="1" x="41" y="10"/>
				  <tile type="regTile" graphic="1" x="41" y="9"/>
				  <tile type="regTile" graphic="1" x="42" y="9"/>
				  <tile type="regTile" graphic="1" x="42" y="8"/>
				  <tile type="regTile" graphic="1" x="41" y="8"/>
				  <tile type="regTile" graphic="1" x="40" y="9"/>
				  <tile type="regTile" graphic="1" x="37" y="10"/>
				  <tile type="regTile" graphic="1" x="36" y="10"/>
				  <tile type="regTile" graphic="1" x="34" y="9"/>
				  <tile type="regTile" graphic="1" x="35" y="10"/>
				  <tile type="regTile" graphic="1" x="44" y="7"/>
				  <tile type="regTile" graphic="1" x="45" y="6"/>
				  <tile type="regTile" graphic="1" x="46" y="6"/>
				  <tile type="regTile" graphic="1" x="46" y="5"/>
				  <tile type="regTile" graphic="1" x="47" y="4"/>
				  <tile type="regTile" graphic="1" x="48" y="3"/>
				  <tile type="regTile" graphic="1" x="49" y="1"/>
				  <tile type="regTile" graphic="1" x="50" y="0"/>
				  <tile type="regTile" graphic="1" x="50" y="-1"/>
				  <tile type="regTile" graphic="1" x="50" y="1"/>
				  <tile type="regTile" graphic="1" x="50" y="2"/>
				  <tile type="regTile" graphic="1" x="49" y="2"/>
				  <tile type="regTile" graphic="1" x="49" y="3"/>
				  <tile type="jumpTile" graphic="1" x="48" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="47" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="46" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="45" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="44" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="43" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="42" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="41" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="40" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="39" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="38" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="37" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="36" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="35" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="34" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="33" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="32" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="31" y="-4"/>
				  <tile type="jumpTile" graphic="1" x="30" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="29" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="28" y="-6"/>
				  <tile type="jumpTile" graphic="1" x="28" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="27" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="26" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="25" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="24" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="23" y="-7"/>
				  <tile type="jumpTile" graphic="1" x="21" y="-2"/>
				  <tile type="jumpTile" graphic="1" x="20" y="-2"/>
				  <tile type="jumpTile" graphic="1" x="19" y="-2"/>
				  <tile type="jumpTile" graphic="1" x="18" y="-2"/>
				  <tile type="jumpTile" graphic="1" x="17" y="-2"/>
				  <tile type="jumpTile" graphic="1" x="16" y="-2"/>
				  <tile type="jumpTile" graphic="1" x="23" y="-5"/>
				  <tile type="jumpTile" graphic="1" x="22" y="-5"/>
				  <tile type="jumpTile" graphic="1" x="21" y="-5"/>
				  <tile type="jumpTile" graphic="1" x="13" y="-3"/>
				  <tile type="jumpTile" graphic="1" x="12" y="-3"/>
				  <tile type="jumpTile" graphic="1" x="11" y="-3"/>
				  <tile type="jumpTile" graphic="1" x="10" y="-5"/>
				  <tile type="regTile" graphic="2" x="-10" y="-5"/>
				  <tile type="regTile" graphic="2" x="-10" y="-4"/>
				  <tile type="regTile" graphic="2" x="-10" y="-3"/>
				  <tile type="regTile" graphic="3" x="-9" y="-5"/>
				  <tile type="regTile" graphic="3" x="-9" y="-4"/>
				  <tile type="regTile" graphic="3" x="-8" y="-4"/>
				  <tile type="regTile" graphic="3" x="-9" y="-3"/>
				  <tile type="regTile" graphic="3" x="-8" y="-5"/>
				  <tile type="regTile" graphic="3" x="-8" y="-3"/>
				  <tile type="regTile" graphic="3" x="-8" y="-2"/>
				  <tile type="regTile" graphic="3" x="-9" y="-2"/>
				  <tile type="regTile" graphic="3" x="-9" y="-1"/>
				  <tile type="regTile" graphic="3" x="-9" y="0"/>
				  <tile type="regTile" graphic="3" x="-8" y="0"/>
				  <tile type="regTile" graphic="3" x="-8" y="1"/>
				  <tile type="regTile" graphic="3" x="-8" y="2"/>
				  <tile type="regTile" graphic="3" x="-8" y="3"/>
				  <tile type="regTile" graphic="3" x="-8" y="4"/>
				  <tile type="regTile" graphic="3" x="-8" y="5"/>
				  <tile type="regTile" graphic="3" x="-9" y="5"/>
				  <tile type="regTile" graphic="3" x="-9" y="4"/>
				  <tile type="regTile" graphic="3" x="-9" y="3"/>
				  <tile type="regTile" graphic="3" x="-9" y="2"/>
				  <tile type="regTile" graphic="3" x="-9" y="1"/>
				  <tile type="regTile" graphic="3" x="-8" y="-1"/>
				  <tile type="regTile" graphic="3" x="-9" y="6"/>
				  <tile type="regTile" graphic="3" x="-9" y="7"/>
				  <tile type="regTile" graphic="3" x="-9" y="8"/>
				  <tile type="regTile" graphic="3" x="-8" y="8"/>
				  <tile type="regTile" graphic="3" x="-8" y="9"/>
				  <tile type="regTile" graphic="3" x="-8" y="7"/>
				  <tile type="regTile" graphic="3" x="-9" y="9"/>
				  <tile type="regTile" graphic="3" x="-8" y="6"/>
				  <tile type="regTile" graphic="3" x="-8" y="10"/>
				  <tile type="regTile" graphic="3" x="-9" y="10"/>
				  <tile type="regTile" graphic="2" x="-8" y="11"/>
				  <tile type="regTile" graphic="2" x="-9" y="11"/>
				  <tile type="regTile" graphic="2" x="-10" y="10"/>
				  <tile type="regTile" graphic="2" x="-10" y="11"/>
				  <tile type="regTile" graphic="2" x="-10" y="9"/>
				  <tile type="regTile" graphic="2" x="-10" y="8"/>
				  <tile type="regTile" graphic="2" x="-10" y="7"/>
				  <tile type="regTile" graphic="2" x="-10" y="6"/>
				  <tile type="regTile" graphic="2" x="-10" y="5"/>
				  <tile type="regTile" graphic="2" x="-10" y="4"/>
				  <tile type="regTile" graphic="2" x="-10" y="3"/>
				  <tile type="regTile" graphic="2" x="-10" y="2"/>
				  <tile type="regTile" graphic="2" x="-10" y="1"/>
				  <tile type="regTile" graphic="2" x="-10" y="0"/>
				  <tile type="regTile" graphic="2" x="-10" y="-1"/>
				  <tile type="regTile" graphic="2" x="-10" y="-2"/>
				  <tile type="regTile" graphic="1" x="-4" y="11"/>
				  <tile type="regTile" graphic="4" x="-5" y="11"/>
				  <tile type="regTile" graphic="4" x="-5" y="12"/>
				  <tile type="regTile" graphic="4" x="-5" y="13"/>
				  <tile type="regTile" graphic="4" x="-5" y="14"/>
				  <tile type="regTile" graphic="4" x="-5" y="15"/>
				  <tile type="regTile" graphic="4" x="-6" y="15"/>
				  <tile type="regTile" graphic="4" x="-7" y="15"/>
				  <tile type="regTile" graphic="4" x="-8" y="15"/>
				  <tile type="regTile" graphic="4" x="-9" y="15"/>
				  <tile type="regTile" graphic="4" x="-10" y="15"/>
				  <tile type="regTile" graphic="4" x="-11" y="15"/>
				  <tile type="regTile" graphic="4" x="-12" y="15"/>
				  <tile type="regTile" graphic="4" x="-13" y="15"/>
				  <tile type="regTile" graphic="4" x="-14" y="15"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="10"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="8"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="6"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="5"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="4"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="3"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="-5"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="-3"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="-1"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="1"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="7"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="11"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="9"/>
				  <tile type="jumpTile" graphic="2" x="-13" y="13"/>
				  <tile type="jumpTile" graphic="2" x="-14" y="13"/>
				  <tile type="jumpTile" graphic="2" x="-12" y="13"/>
				  <tile type="jumpTile" graphic="2" x="-11" y="13"/>
				  <tile type="regTile" graphic="4" x="-15" y="15"/>
				  <tile type="regTile" graphic="2" x="-15" y="14"/>
				  <tile type="regTile" graphic="2" x="-15" y="13"/>
				  <tile type="regTile" graphic="2" x="-15" y="12"/>
				  <tile type="regTile" graphic="2" x="-15" y="11"/>
				  <tile type="regTile" graphic="2" x="-15" y="10"/>
				  <tile type="regTile" graphic="2" x="-15" y="9"/>
				  <tile type="regTile" graphic="2" x="-15" y="8"/>
				  <tile type="regTile" graphic="2" x="-15" y="7"/>
				  <tile type="regTile" graphic="2" x="-15" y="6"/>
				  <tile type="regTile" graphic="2" x="-15" y="5"/>
				  <tile type="regTile" graphic="2" x="-15" y="4"/>
				  <tile type="regTile" graphic="2" x="-15" y="3"/>
				  <tile type="regTile" graphic="2" x="-15" y="2"/>
				  <tile type="regTile" graphic="2" x="-15" y="1"/>
				  <tile type="regTile" graphic="2" x="-15" y="0"/>
				  <tile type="regTile" graphic="2" x="-15" y="-1"/>
				  <tile type="regTile" graphic="2" x="-15" y="-2"/>
				  <tile type="regTile" graphic="2" x="-15" y="-3"/>
				  <tile type="regTile" graphic="2" x="-15" y="-4"/>
				  <tile type="regTile" graphic="2" x="-15" y="-5"/>
				  <tile type="regTile" graphic="1" x="-4" y="12"/>
				  <tile type="regTile" graphic="1" x="-3" y="12"/>
				  <tile type="regTile" graphic="1" x="-2" y="12"/>
				  <tile type="regTile" graphic="1" x="-1" y="12"/>
				  <tile type="regTile" graphic="1" x="0" y="12"/>
				  <tile type="regTile" graphic="1" x="1" y="12"/>
				  <tile type="regTile" graphic="1" x="2" y="12"/>
				  <tile type="regTile" graphic="1" x="3" y="12"/>
				  <tile type="regTile" graphic="1" x="4" y="12"/>
				  <tile type="regTile" graphic="1" x="5" y="12"/>
				  <tile type="regTile" graphic="1" x="6" y="12"/>
				  <tile type="regTile" graphic="1" x="7" y="12"/>
				  <tile type="regTile" graphic="1" x="9" y="12"/>
				  <tile type="regTile" graphic="1" x="10" y="12"/>
				  <tile type="regTile" graphic="1" x="11" y="12"/>
				  <tile type="regTile" graphic="1" x="12" y="12"/>
				  <tile type="regTile" graphic="1" x="13" y="12"/>
				  <tile type="regTile" graphic="1" x="14" y="12"/>
				  <tile type="regTile" graphic="1" x="-4" y="13"/>
				  <tile type="regTile" graphic="1" x="-3" y="13"/>
				  <tile type="regTile" graphic="1" x="-2" y="13"/>
				  <tile type="regTile" graphic="1" x="-1" y="13"/>
				  <tile type="regTile" graphic="1" x="0" y="13"/>
				  <tile type="regTile" graphic="1" x="1" y="13"/>
				  <tile type="regTile" graphic="1" x="2" y="13"/>
				  <tile type="regTile" graphic="1" x="3" y="13"/>
				  <tile type="regTile" graphic="1" x="4" y="13"/>
				  <tile type="regTile" graphic="1" x="5" y="13"/>
				  <tile type="regTile" graphic="1" x="6" y="13"/>
				  <tile type="regTile" graphic="1" x="7" y="13"/>
				  <tile type="regTile" graphic="1" x="8" y="13"/>
				  <tile type="regTile" graphic="1" x="9" y="13"/>
				  <tile type="regTile" graphic="1" x="10" y="13"/>
				  <tile type="regTile" graphic="1" x="11" y="13"/>
				  <tile type="regTile" graphic="1" x="12" y="13"/>
				  <tile type="regTile" graphic="1" x="8" y="12"/>
				  <tile type="regTile" graphic="2" x="-15" y="-6"/>
				  <tile type="regTile" graphic="2" x="-15" y="-7"/>
				  <tile type="regTile" graphic="2" x="-15" y="-8"/>
				  <tile type="regTile" graphic="2" x="-15" y="-9"/>
				  <tile type="regTile" graphic="2" x="-15" y="-10"/>
				  <tile type="regTile" graphic="2" x="-15" y="-11"/>
				  <tile type="regTile" graphic="2" x="-15" y="-12"/>
				  <tile type="regTile" graphic="2" x="-15" y="-13"/>
				  <tile type="regTile" graphic="2" x="-15" y="-14"/>
				  <tile type="regTile" graphic="2" x="-15" y="-15"/>
				  <tile type="regTile" graphic="2" x="-15" y="-16"/>
				  <tile type="regTile" graphic="2" x="-15" y="-17"/>
				  <tile type="regTile" graphic="1" x="51" y="-4"/>
				  <tile type="regTile" graphic="1" x="51" y="-5"/>
				  <tile type="regTile" graphic="1" x="51" y="-6"/>
				  <tile type="regTile" graphic="1" x="51" y="-7"/>
				  <tile type="regTile" graphic="1" x="51" y="-8"/>
				  <tile type="regTile" graphic="1" x="51" y="-9"/>
				  <tile type="regTile" graphic="1" x="51" y="-10"/>
				  <tile type="regTile" graphic="1" x="51" y="-11"/>
				  <tile type="regTile" graphic="1" x="51" y="-12"/>
				  <tile type="regTile" graphic="1" x="51" y="-13"/>
				  <tile type="regTile" graphic="1" x="51" y="-14"/>
				  <tile type="regTile" graphic="1" x="51" y="-15"/>
				  <tile type="regTile" graphic="1" x="51" y="-16"/>
				  <tile type="regTile" graphic="1" x="51" y="-17"/>
				  <marker type="1" x="1" y="-1"/>
				  <mapRect x="-15" y="-17" width="67" height="33"/>
				</data>
		}
	}
}